const NEXT_ACTION_ROWS = [
  { rowId: 'M6-2X-0001', primaryReason: 'GLOBAL_STOP_ACTIVE', action: 'OPEN_AUDIT_LOG', runbookLabel: '7-2-3', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0002', primaryReason: 'FEATURE_DISABLED_NOTIFICATION', action: 'OPEN_AUDIT_LOG', runbookLabel: '7-2-3', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0003', primaryReason: 'FEATURE_DISABLED_FAQ', action: 'OPEN_AUDIT_LOG', runbookLabel: '7-2-3', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0004', primaryReason: 'FEATURE_DISABLED_SCENARIO', action: 'OPEN_AUDIT_LOG', runbookLabel: '7-2-3', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0005', primaryReason: 'HOUSEHOLD_STOP_NOTIFICATIONS', action: 'OPEN_AUDIT_LOG', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0006', primaryReason: 'SYSTEM_ERROR', action: 'CREATE_INCIDENT', runbookLabel: '7-2-1', requiresRole: 'operator', requiresReason: true, auditRequired: true },
  { rowId: 'M6-2X-0007', primaryReason: 'INTERNAL_ERROR', action: 'CREATE_INCIDENT', runbookLabel: '7-2-1', requiresRole: 'operator', requiresReason: true, auditRequired: true },
  { rowId: 'M6-2X-0008', primaryReason: 'CONTEXT_SYSTEM_HEALTH_RED', action: 'CREATE_INCIDENT', runbookLabel: '7-2-1', requiresRole: 'operator', requiresReason: true, auditRequired: true },
  { rowId: 'M6-2X-0009', primaryReason: 'UNKNOWN_REASON', action: 'CREATE_INCIDENT', runbookLabel: '7-2-1', requiresRole: 'operator', requiresReason: true, auditRequired: true },
  { rowId: 'M6-2X-0010', primaryReason: 'DELIVERY_FAILURE', action: 'RETRY_DELIVERY', runbookLabel: '7-2-2', requiresRole: 'operator', requiresReason: true, auditRequired: true },
  { rowId: 'M6-2X-0011', primaryReason: 'DELIVERY_FAILURE_SPIKE', action: 'CREATE_INCIDENT', runbookLabel: '7-2-1', requiresRole: 'operator', requiresReason: true, auditRequired: true },
  { rowId: 'M6-2X-0012', primaryReason: 'INCIDENT_UNDER_INVESTIGATION', action: 'OPEN_INCIDENT', runbookLabel: '7-2-1', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0013', primaryReason: 'CONSENT_MISSING_NOTIFY', action: 'TRIGGER_RECONSENT_FLOW', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0014', primaryReason: 'CONSENT_MISSING_FAQ', action: 'TRIGGER_RECONSENT_FLOW', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0015', primaryReason: 'CONSENT_VERSION_OUTDATED', action: 'TRIGGER_RECONSENT_FLOW', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0016', primaryReason: 'CONSENT_SCOPE_LIMITED', action: 'OPEN_CONSENT_AUDIT', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0017', primaryReason: 'CONSENT_CHILD_SCOPE_MISSING', action: 'TRIGGER_RECONSENT_FLOW', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0018', primaryReason: 'PLAN_STATUS_PAST_DUE', action: 'OPEN_BILLING_RECONCILIATION', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0019', primaryReason: 'PLAN_STATUS_CANCELED', action: 'OPEN_BILLING_RECONCILIATION', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0020', primaryReason: 'PLAN_FEATURE_LOCKED', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0021', primaryReason: 'PLAN_LIMITED_DEPTH', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0022', primaryReason: 'PLAN_RATE_LIMIT', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0023', primaryReason: 'RISK_TEMPLATE_HIGH', action: 'DISABLE_TEMPLATE', runbookLabel: '7-1-2', requiresRole: 'editor', requiresReason: true, auditRequired: true },
  { rowId: 'M6-2X-0024', primaryReason: 'RISK_LLM_HIGH', action: 'FLAG_FAQ_FOR_REVIEW', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0025', primaryReason: 'RISK_LLM_HALLUCINATION_SUSPECT', action: 'FLAG_FAQ_FOR_REVIEW', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0026', primaryReason: 'LLM_MEDICAL_GUARD', action: 'FLAG_FAQ_FOR_REVIEW', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0027', primaryReason: 'LLM_LEGAL_GUARD', action: 'FLAG_FAQ_FOR_REVIEW', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0028', primaryReason: 'LLM_LOW_CONFIDENCE', action: 'FLAG_FAQ_FOR_REVIEW', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0029', primaryReason: 'LLM_REFUSAL_TRIGGERED', action: 'CREATE_INCIDENT', runbookLabel: '7-2-1', requiresRole: 'operator', requiresReason: true, auditRequired: true },
  { rowId: 'M6-2X-0030', primaryReason: 'LLM_HIGH_RISK_QUERY', action: 'FLAG_FAQ_FOR_REVIEW', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0031', primaryReason: 'SOURCE_UNVERIFIED', action: 'OPEN_SOURCE', runbookLabel: '7-1-2', requiresRole: 'editor', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0032', primaryReason: 'SOURCE_OUTDATED', action: 'OPEN_SOURCE', runbookLabel: '7-1-2', requiresRole: 'editor', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0033', primaryReason: 'SOURCE_CONFLICT', action: 'OPEN_SOURCE', runbookLabel: '7-1-2', requiresRole: 'editor', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0034', primaryReason: 'RISK_SOURCE_LOW_CONFIDENCE', action: 'OPEN_SOURCE', runbookLabel: '7-1-2', requiresRole: 'editor', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0036', primaryReason: 'CONTEXT_QUIET_HOURS_DELAYED', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0037', primaryReason: 'CONTEXT_RATE_LIMIT', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0038', primaryReason: 'CONTEXT_DEDUPE_SUPPRESSED', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0039', primaryReason: 'CONTEXT_PROVIDER_OUTAGE', action: 'CREATE_INCIDENT', runbookLabel: '7-2-1', requiresRole: 'operator', requiresReason: true, auditRequired: true },
  { rowId: 'M6-2X-0040', primaryReason: 'CONTEXT_RETRY_EXCEEDED', action: 'CREATE_INCIDENT', runbookLabel: '7-2-1', requiresRole: 'operator', requiresReason: true, auditRequired: true },
  { rowId: 'M6-2X-0041', primaryReason: 'EVENT_TOO_SOON', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0042', primaryReason: 'TEMPLATE_DISABLED', action: 'OPEN_TEMPLATE_REVIEW', runbookLabel: '7-1-2', requiresRole: 'editor', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0043', primaryReason: 'TEMPLATE_DEPRECATED', action: 'OPEN_TEMPLATE_REVIEW', runbookLabel: '7-1-2', requiresRole: 'editor', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0044', primaryReason: 'DATA_REQUEST_OPEN', action: 'OPEN_DATA_REQUEST', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0045', primaryReason: 'HOUSEHOLD_DELETION_IN_PROGRESS', action: 'OPEN_DATA_REQUEST', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0046', primaryReason: 'VENDOR_EXPOSURE', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0047', primaryReason: 'VENDOR_INQUIRY', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0048', primaryReason: 'VENDOR_FEEDBACK', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0049', primaryReason: 'EXPERIENCE_SOURCE_USED', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0050', primaryReason: 'EXPERIENCE_SOURCE_LOW_CONFIDENCE', action: 'OPEN_SOURCE', runbookLabel: '7-2-4', requiresRole: 'editor', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0051', primaryReason: 'EXPERIENCE_SOURCE_CONFLICT', action: 'OPEN_SOURCE', runbookLabel: '7-2-4', requiresRole: 'editor', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0052', primaryReason: 'EXPERIENCE_SOURCE_OUTDATED', action: 'OPEN_SOURCE', runbookLabel: '7-2-4', requiresRole: 'editor', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0053', primaryReason: 'REVIEW_SOURCE_USED', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0054', primaryReason: 'REVIEW_SOURCE_BIAS_SUSPECT', action: 'OPEN_SOURCE', runbookLabel: '7-2-5', requiresRole: 'editor', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0055', primaryReason: 'REVIEW_SOURCE_LOW_CONFIDENCE', action: 'OPEN_SOURCE', runbookLabel: '7-2-5', requiresRole: 'editor', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0056', primaryReason: 'REVIEW_SOURCE_OUTDATED', action: 'OPEN_SOURCE', runbookLabel: '7-2-5', requiresRole: 'editor', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0057', primaryReason: 'REVIEW_SOURCE_MEDICAL_CAUTION', action: 'OPEN_SOURCE', runbookLabel: '7-2-5', requiresRole: 'editor', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0058', primaryReason: 'INSIGHT_PRESENTED', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0059', primaryReason: 'INSIGHT_REACTION_CAPTURED', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0060', primaryReason: 'INSIGHT_CAUSED_FLOW_CHANGE', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0061', primaryReason: 'PLAN_LIMIT_FREE', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0062', primaryReason: 'PLAN_LIMIT_SOLO', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0063', primaryReason: 'PLAN_LIMIT_FAMILY', action: 'NONE', runbookLabel: '7-1-2', requiresRole: 'viewer', requiresReason: false, auditRequired: false },
  { rowId: 'M6-2X-0064', primaryReason: 'RISK_POLICY_PROHIBITED', action: 'FLAG_FAQ_FOR_REVIEW', runbookLabel: '7-1-2', requiresRole: 'operator', requiresReason: false, auditRequired: false }
];

const NEXT_ACTION_BY_REASON = NEXT_ACTION_ROWS.reduce((index, row) => {
  index[row.primaryReason] = row;
  return index;
}, {});

const CATEGORY_FALLBACK = {
  STOP: 'GLOBAL_STOP_ACTIVE',
  INCIDENT: 'INCIDENT_UNDER_INVESTIGATION',
  SYSTEM: 'SYSTEM_ERROR',
  RISK: 'RISK_TEMPLATE_HIGH',
  REVIEW_SOURCE: 'REVIEW_SOURCE_BIAS_SUSPECT',
  EXPERIENCE_SOURCE: 'EXPERIENCE_SOURCE_LOW_CONFIDENCE',
  SOURCE: 'SOURCE_UNVERIFIED',
  CONSENT: 'CONSENT_MISSING_NOTIFY',
  PLAN: 'PLAN_FEATURE_LOCKED',
  CONTEXT: 'CONTEXT_DEDUPE_SUPPRESSED',
  VENDOR: 'VENDOR_EXPOSURE'
};

module.exports = {
  NEXT_ACTION_ROWS,
  NEXT_ACTION_BY_REASON,
  CATEGORY_FALLBACK
};
